DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Months;

CREATE TABLE Users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Active BOOLEAN NOT NULL,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Username TEXT UNIQUE NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE Transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER NOT NULL,
  CategoryId INTEGER NOT NULL,
  MonthId INTEGER NOT NULL,
  Organization TEXT NOT NULL,
  Amount DECIMAL NOT NULL,
  Date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserId) REFERENCES Users (id),
  FOREIGN KEY (CategoryId) REFERENCES Categories (id),
  FOREIGN KEY (MonthId) REFERENCES Months (id)
);

CREATE TABLE Categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Description TEXT NOT NULL,
  Expense BOOLEAN NOT NULL,
  Recurring BOOLEAN NOT NULL
);

CREATE TABLE Months (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Month TEXT NOT NULL,
  Year TEXT NOT NULL,
  Savings DECIMAL NOT NULL,
  Projected DECIMAL NOT NULL,
  Actual DECIMAL NOT NULL
);